name: Publish on demand
on: workflow_dispatch
jobs:
  build-osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: |
              ~/.konan/dependencies
              ~/.konan/kotlin-native-prebuilt-macos-2.2.0
          key: ${{ runner.os }}-konan-2.2.0
          restore-keys: ${{ runner.os }}-konan-2.2.0
      - name: Build all platforms but JVM
        run: ./gradlew -Dorg.gradle.daemon=false clean build -Djpms=false --build-cache
      - name: Build JVM only
        run: ./gradlew -Dorg.gradle.daemon=false build -Djpms=true --build-cache
      - name: Publish all platforms but JVM to Maven Central
        run: gradle publish -Djpms=false
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_ossrhHeader: ${{ secrets.OSSR_HEADER }}
      - name: Publish JVM only to Maven Central
        run: gradle publish -Djpms=true
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_ossrhHeader: ${{ secrets.OSSR_HEADER }}
      - name: Transfer from OSSRH Staging API to Central Publisher Portal.
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/org.ufoss
          configuration: '{ "method": "POST", "headers": {"Authorization": "Bearer ${{ secrets.OSSR_HEADER }}"} }'
