name: Test publish on demand
on: workflow_dispatch
jobs:
  build-osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
              ~/.konan/dependencies
              ~/.konan/kotlin-native-prebuilt-macos-1.5.21
          key: ${{ runner.os }}-konan-1.5.21
          restore-keys: ${{ runner.os }}-konan-1.5.21
      - name: Build with Gradle
        run: ./gradlew -Dorg.gradle.daemon=false clean build --build-cache
      - name: Publish to GitHub Packages
        run: gradle publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSR_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSR_PASSWORD }}
