name: Publish on demand
on: workflow_dispatch
jobs:
  build-osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
              ~/.konan/dependencies
              ~/.konan/kotlin-native-prebuilt-macos-2.1.0
          key: ${{ runner.os }}-konan-2.1.0
          restore-keys: ${{ runner.os }}-konan-2.1.0
      - name: Build Mobile only
        run: ./gradlew -Dorg.gradle.daemon=false clean build -Djpms=false --build-cache
      - name: Build JPMS (Jigsaw JVM only)
        run: ./gradlew -Dorg.gradle.daemon=false build -Djpms=true --build-cache
      - name: Publish Mobile only to Maven Central
        run: gradle publish -Djpms=false
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSR_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSR_PASSWORD }}
      - name: Publish JPMS (Jigsaw JVM only) to Maven Central
        run: gradle publish -Djpms=true
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSR_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSR_PASSWORD }}
