name: Test build on demand
on: workflow_dispatch
jobs:
  build-osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
              ~/.konan/dependencies
              ~/.konan/kotlin-native-prebuilt-macos-1.4.10
          key: ${{ runner.os }}-konan-1.4.10
          restore-keys: ${{ runner.os }}-konan-1.4.10
      - name: Build with Gradle
        run: ./gradlew -Dorg.gradle.daemon=false clean buildNeeded --build-cache
