name: Build on demand
on: workflow_dispatch
jobs:
  build-osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: |
              ~/.konan/dependencies
              ~/.konan/kotlin-native-prebuilt-macos-2.2.0
          key: ${{ runner.os }}-konan-2.2.0
          restore-keys: ${{ runner.os }}-konan-2.2.0
      - name: Build with all platforms
        run: ./gradlew -Dorg.gradle.daemon=false clean build -Djpms=false --build-cache
      - name: Build JPMS (Jigsaw JVM only)
        run: ./gradlew -Dorg.gradle.daemon=false clean build -Djpms=true --build-cache
